"""DM Agent prompts."""

from backend.agents.prompts.assistant import (
    COMBAT_NARRATION_PROMPT,
    ENCOUNTER_PROMPT,
    ENCOUNTER_TACTICS_PROMPT,
    NPC_DIALOGUE_PROMPT,
    NPC_PROMPT,
    RULES_LOOKUP_PROMPT,
    SCENE_DESCRIPTION_PROMPT,
    SESSION_HOOK_PROMPT,
    SESSION_RECAP_PROMPT,
    SYSTEM_PROMPT,
)

__all__ = [
    "SYSTEM_PROMPT",
    "RULES_LOOKUP_PROMPT",
    "ENCOUNTER_PROMPT",
    "NPC_PROMPT",
    "SESSION_RECAP_PROMPT",
    "SCENE_DESCRIPTION_PROMPT",
    "COMBAT_NARRATION_PROMPT",
    "NPC_DIALOGUE_PROMPT",
    "ENCOUNTER_TACTICS_PROMPT",
    "SESSION_HOOK_PROMPT",
]
